"""
Django settings for parcial2_prog_iv project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Usa la variable de entorno, si no existe (local), usa la clave insegura por defecto
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure--ie+lxato@-zl!$jkdd$f+ukx=h1g=b3cdu$$ygg%0%s-7exf*')

# SECURITY WARNING: don't run with debug turned on in production!
# En Render DEBUG debe ser False, en la PC True
DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = ['*'] # En producción idealmente poner el dominio de Render


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'alumnos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'parcial2_prog_iv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'parcial2_prog_iv.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# CONFIGURACIÓN DE BASE DE DATOS (Versión Robusta)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Solo si estamos en Render y existe la variable DATABASE_URL, usamos PostgreSQL
# (Esto previene que falle si la variable no existe)
db_from_env = dj_database_url.config(conn_max_age=600)
if db_from_env:
    DATABASES['default'].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Carpeta donde Django junta todos los estilos antes de subir
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Habilita la compresión y almacenamiento en cache
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================
# --- Config. para EMAIL ---
# ==========================

# ESTO HACE QUE EL MAIL SE VEA EN EL LOG Y NO SE MANDE POR GMAIL
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # La que va
EMAIL_HOST = 'smtp-relay.brevo.com'

EMAIL_PORT = 587
EMAIL_USE_TLS = True
# EMAIL_USE_SSL = True # (Más seguro y directo)

EMAIL_HOST_USER = 'cristiangcabral@gmail.com' # EL DE Brevo
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD') # La clave larga de Brevo (en Render)

DEFAULT_FROM_EMAIL = 'cristiangcabral@gmail.com'


# ==========================
# --- Config. para LOGINS ---
# ==========================
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'